################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
configs:
  nginx.conf:
    file: /run/configs/etc/nginx/nginx.conf
secrets:
  default.conf:
    file: /run/secrets/etc/nginx/conf.d/default.conf
services:
  nlb:
    configs:
    - mode: 0400
      source: nginx.conf
      target: /etc/nginx/nginx.conf
    secrets:
    - mode: 0400
      source: default.conf
      target: /etc/nginx/conf.d/default.conf
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: academiaonline/nginx:8.0
    ports:
    - "6443:8080"
version: '3.8'
################################################################################
