################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
configs:
  nginx.conf:
    file: /run/configs/etc/nginx/nginx.conf
secrets:
  default.conf:
    file: /run/secrets/etc/nginx/conf.d/default.conf
services:
  nlb:
    configs:
    - mode: 0400
      source: nginx.conf
      target: /etc/nginx/nginx.conf
    expose:
    - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s
    secrets:
    - mode: 0400
      source: default.conf
      target: /etc/nginx/conf.d/default.conf
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    image: academiaonline/nginx:latest
    ports:
    - "6443:8080"
version: '3.8'
################################################################################
