################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nlb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlb
  template: 
    metadata:
      labels:
        app: nlb
    spec:
      containers: 
      - name: nginx
        image: secobau/nginx:7.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100M
          requests:
            cpu: 100m
            memory: 100M          
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nlb
spec:
  ingress:
  - ports:
    - port: 8080
  podSelector:
    matchLabels:
      app: nlb
---
apiVersion: v1
kind: Service
metadata: 
  name: nlb
spec:
  ports:
  - port: 6443
    nodePort: 30000
    targetPort: 8080
  selector:
    app: nlb
  type: NodePort
---  
