################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: CI                                                                       #
on:                                                                            #
  push:                                                                        #
    branches:                                                                  #
    - docker                                                                   #
jobs:                                                                          #
  docker:                                                                      #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: test                                                               #
      run: |                                                                   #
        set -x                                                                 ;
                                                                               #
        branch=$(basename $GITHUB_REF)                                         ;
        project=$(basename $GITHUB_REPOSITORY)                                 ;
                                                                               #
        sudo cp -rv run/* /run                                                 ;
                                                                               #
        docker run -d -p 80:8080                                               \
          --cpus "0.1" -m 100m --memory-reservation 100m                       \
          --health-cmd "netstat -ln | grep -q 8080"                            \
          --health-interval=10s                                                \
          --health-retries=3                                                   \
          --health-start-period=30s                                            \
          --health-timeout=1s                                                  \
          --volume /run/configs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  \
          --volume                                                             \
            /run/secrets/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro \
          --name test academiaonline/nginx:latest                              ;
                                                                               #
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            docker exec test ps                                                \
            |                                                                  \
            grep "1.*nginx: master process"                                    \
            &&                                                                 \
            break                                                              ;
          done                                                                 ;
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            docker logs test                                                   \
              2>& 1                                                            \
            |                                                                  \
            grep "start worker processes"                                      \
            &&                                                                 \
            break                                                              ;
          done                                                                 ;
                                                                               #
  swarm:                                                                       #
    env:                                                                       #
      mode: swarm                                                              #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: test                                                               #
      run: |                                                                   #
        set -x                                                                 ;
                                                                               #
        branch=$(basename $GITHUB_REF)                                         ;
        project=$(basename $GITHUB_REPOSITORY)                                 ;
                                                                               #
        compose=etc/$mode/$project.yaml                                        ;
                                                                               #
        docker swarm init                                                      ;
        sed -i /node.role/s/worker/manager/ $compose                           ;
                                                                               #
        sudo cp -rv run/* /run                                                 ;
                                                                               #
        docker stack deploy -c $compose $project                               ;
                                                                               #
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            docker service ls                                                  \
            |                                                                  \
            grep "$project.*replicated.*\([0-9]\)/\1.*8080"                    \
            &&                                                                 \
            break                                                              ;
          done                                                                 ;
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            docker service logs ${project}_${project}                          \
              2>& 1                                                            \
            |                                                                  \
            grep "start worker processes"                                      \
            &&                                                                 \
            break                                                              ;
          done                                                                 ;
                                                                               #
  kubernetes:                                                                  #
    env:                                                                       #
      mode: kubernetes                                                         #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: test                                                               #
      run: |                                                                   #
        set -x                                                                 ;
                                                                               #
        branch=$(basename $GITHUB_REF)                                         ;
        project=$(basename $GITHUB_REPOSITORY)                                 ;
                                                                               #
        sudo cp -rv run/* /run                                                 ;
                                                                               #
        compose=etc/$mode/$project.yaml                                        ;
                                                                               #
        uuid=$( md5sum $compose | cut -d' ' -f1 )                              ;
        git clone --single-branch -b v1.0                                      \
          https://github.com/academiaonline/kubernetes $uuid                   ;
        path=$uuid/bin/standalone/ubuntu18/install.sh                          ;
        source $path                                                           ;
        path=$uuid/bin/configs-secrets-gen.sh                                  ;
        source $path                                                           ;
        rm -rf $uuid                                                           ;
                                                                               #
        sed -i /imagePullPolicy/s/Always/Never/ $compose                       ;
                                                                               #
        kubectl apply -f $compose                                              ;
                                                                               #
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            kubectl get deploy | grep "$project.*\([0-9]\)/\1" && break        ;
          done                                                                 ;
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            kubectl get svc | grep "$project.*ClusterIP.*8080/TCP" && break    ;
          done                                                                 ;
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            kubectl logs deploy/$project                                       \
            |                                                                  \
            grep "start worker processes"                                      \
            &&                                                                 \
            break                                                              ;
          done                                                                 ;
################################################################################
