# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  #  branches: [ master ]
  #pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  swarm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #- name: Checkout
    #  uses: actions/checkout@v2

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout test
      uses: actions/checkout@v2
#     with:
#       ref: test

    # Runs a set of commands using the runners shell
    - name: Test the app
      id: test
      run: |
        docker swarm init
        compose=etc/docker/swarm/docker-compose.yaml
        sed -i s/worker/manager/ $compose
        sudo cp -rv ./run/configs /run
        docker stack deploy -c $compose nlb
        sleep 1
        docker service ls
        sleep 1
        docker service ls
        sleep 1
        docker service ls
        sleep 1
        docker service ls
        sleep 1
        docker service ls
        sleep 1
        docker service ls
        sleep 1
        docker service ls
